import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

/**
 * eslint-config-next 16 ships native flat configs, so they are spread straight
 * in. Routing them through `FlatCompat` (the eslintrc bridge) made ESLint 9
 * try to JSON.stringify a plugin object that references itself, and every run
 * died with "Converting circular structure to JSON" before linting a file.
 *
 * Ignores live here too: flat config does not read `.eslintignore`.
 */
const eslintConfig = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Prisma's generated client — regenerated by `prisma generate`, not ours.
      "src/generated/**",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
];

export default eslintConfig;
